name: Frontend Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_BACKEND_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_BACKEND_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_FRONTEND_APP_NAME
        env:
          HEROKU_FRONTEND_APP_NAME: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
      - name: Push to Heroku
        run: git subtree push --prefix client heroku master