# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull request checker

on:
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install the client dependencies
      run: yarn install --frozen-lockfile
      working-directory: client
    - name: Frontend test coverage
      run: yarn test
      working-directory: client
    - name: Install the server dependencies
      run: yarn install --frozen-lockfile
      working-directory: server
    - name: Backend test coverage
      run: yarn test
      working-directory: server
